CREDENTIAL_TYPE_PASSWORD = "password"
CREDENTIAL_TYPE_PRIVATE_KEY = "privateKey"
CREDENTIAL_TYPE_CHOICES = (
    (CREDENTIAL_TYPE_PASSWORD, "password"),
    (CREDENTIAL_TYPE_PRIVATE_KEY, "privateKey")
)
