# Generated by Django 2.1.15 on 2020-02-20 08:34

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ko_host', '0001_initial'),
        ('ko_package', '0001_initial'),
        ('ansible_api', '0003_auto_20200220_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Project')),
                ('configs', common.models.JsonDictTextField(default={})),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ko_package.Package')),
            ],
            bases=('ansible_api.project',),
        ),
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=128, unique=True)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('meta', common.models.JsonDictTextField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(allow_unicode=True, max_length=128, unique=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ko_cluster.Cluster')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ko_host.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ansible_api.group',),
        ),
    ]
