# Generated by Django 2.1.15 on 2020-02-17 07:08

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ko_cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resource', models.SlugField(max_length=128, unique=True)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('meta', common.models.JsonDictTextField(default={})),
            ],
        ),
    ]
