# Generated by Django 2.1.15 on 2020-02-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ko_cluster', '0002_configfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configfile',
            old_name='resource',
            new_name='name',
        ),
    ]
