# Generated by Django 2.1.15 on 2020-02-16 08:14

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ko_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('reason', models.CharField(max_length=256, null=True)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(default=22)),
                ('vars', common.models.JsonDictTextField(default={})),
                ('meta', common.models.JsonDictTextField(default={})),
                ('comment', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid name consisting of Unicode letters, numbers, underscores, or hyphens, or dot', regex='^[a-zA-Z0-9_\\-\\.]+$')])),
                ('state', models.CharField(choices=[('RUNNING', 'running'), ('CREATING', 'creating'), ('UNKNOWN', 'unknown'), ('WARNING', 'warning')], default='UNKNOWN', max_length=128)),
                ('basic', common.models.JsonDictTextField(default={})),
                ('connected', models.BooleanField(default=True)),
                ('conditions', models.ManyToManyField(to='ko_host.Condition')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ko_system.Credential')),
                ('gpus', models.ManyToManyField(to='ko_host.GPU')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ('size',),
            },
        ),
        migrations.AddField(
            model_name='host',
            name='volumes',
            field=models.ManyToManyField(to='ko_host.Volume'),
        ),
    ]
