HOST_STATUS_RUNNING = "RUNNING"
HOST_STATUS_CREATING = "CREATING"
HOST_STATUS_WARNING = "WARNING"
HOST_STATUS_UNKNOWN = "UNKNOWN"
DEPLOY_TEMPLATE_CHOICES = (
    (HOST_STATUS_RUNNING, 'running'),
    (HOST_STATUS_CREATING, 'creating'),
    (HOST_STATUS_UNKNOWN, "unknown"),
    (HOST_STATUS_WARNING, "warning"),
)

HOST_CPU_THRESHOLD = 70
HOST_MEMORY_THRESHOLD = 70
